# Site settings for theme `hugo-theme-cactus-plus`

baseurl = "/"
languageCode = "en"
publishDir = "../docs"
title = "It's Dan :)"
theme = "hugo-theme-cactus-plus"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

# add `languages` to enable translation.
[languages]
[languages.en]
	weight = 1

[languages.id]
	weight = 2

[taxonomies]
   tag = "tags"
   # category = "categories"

[params]
	useCDN = false
	author = "wzulfikar"
	description = "Just another blog."
	bio = "Communication, and Technology."

	twitter = "wzulfikar"
	# facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = true
	googleAnalytics = "UA-XXXXXXXX-X"

	# Set the value to your baidu analysis code if you want to use baidu analytics
	enableBaiduAnalytics = false
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = ["/css/custom.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = "RSS"

	olderPosts = ""
	newerPosts = ""
	copyright = " "

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	# facebook-square = "https://www.facebook.com/nodejh"
	twitter-square = "https://www.twitter.com/wzulfikar"
	github-square = "https://www.github.com/wzulfikar"